---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    type: ram
    author: kumar
spec:
  replicas: 3
  selector: 
    matchLabels: 
      type: ram
      author: kumar
  template:
    metadata:
      name: nginx-pod
      labels: 
        type: ram
        author: kumar
    spec:
      containers:
       - name: mynginx
         image: nginx
         ports:
           - containerPort: 80
             hostPort: 9090
...
